# Generated by Django 2.2.5 on 2019-09-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190908_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookevent',
            old_name='organizer',
            new_name='user',
        ),
        migrations.AddField(
            model_name='bookevent',
            name='first_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookevent',
            name='last_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookevent',
            name='mail',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookevent',
            name='number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
