# Generated by Django 2.2.5 on 2019-09-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190908_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookevent',
            old_name='number',
            new_name='phone_number',
        ),
    ]
