# Generated by Django 2.2.5 on 2019-09-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20190908_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
